name: Local
values:
  - key: base_url
    value: http://localhost:8000
    type: default
  - key: token
    value: ''
    type: secret
  - key: user_id
    value: ''
    type: default
  - key: venue_id
    value: ''
    type: default
  - key: event_id
    value: ''
    type: default
  - key: booking_id
    value: ''
    type: default
