from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Enum as SQLEnum
from uuid import UUID
from app.base import Base, TimestampMixin
from app.enums.roles import UserRole

class User(Base, TimestampMixin):
    __tablename__ = "users"

    # Matches the UUID generated by Supabase Auth (GoTrue)
    id: Mapped[UUID] = mapped_column(primary_key=True)
    
    # User email, indexed for fast O(1) database lookups
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    
    # Basic user attributes
    first_name: Mapped[str] = mapped_column(String(100), nullable=False)
    last_name: Mapped[str] = mapped_column(String(100), nullable=False)
    
    # Role validation stored as VARCHAR for easy future modification
    role: Mapped[UserRole] = mapped_column(
        SQLEnum(UserRole, name="user_role", native_enum=False),
        default=UserRole.USER,
        nullable=False
    )

    # Relationship back-populating to events
    events: Mapped[list["Event"]] = relationship("Event", back_populates="organizer")
    bookings: Mapped[list["Booking"]] = relationship("Booking", back_populates="user")
